### PR TITLE
Added support for search devices

### PR DESCRIPTION
**Pull request by sankarsubramanian**
Ready for Review

### CODE REVIEW

**Comment by kristinpeterson** [comment]
@omab hello! can you please review this PR when you have a moment?

**Comment by majidabdul** [comment]
@omab : Can you please merge?  @attsdk has lost access to merge :(

**Comment by kristinpeterson** [comment]
@omab when you have a moment, could you merge and issue a release?

**Comment by omab** [comment]
@kristinpeterson, merged and `0.4.0` got released into [pipy](https://pypi.python.org/pypi/m2x-mqtt/0.4.0)

**Pull request merged**
